### PR TITLE
Accordion realisations

### PR DESCRIPTION
**Pull request by artrodriguezcabrera**
Hi @mgc-codigo , this is the accordion branch.  Please review this on your local computer.

Within Github Desktop, ensure to Pull so you get the latest changes.  Then you have to switch your branch over to the `accordion-realisations` branch.  Once you have switch, you can pull the code up in VS Code.  Once in VS Code, open the index.html file.  Then you need to run the server by clicking on "Go Live" on the bottom right of VS Code.  This will launch the server on your localhost so you can review. 

Please document any additional changes you need here in comments.  I will review those and then merge this branch into our main. If there are no changes you need, then simply reassign this Pull Request back to me and I will merge later.

Thank you!

### CODE REVIEW

**Comment by mgc-codigo** [comment]
[FRENCH ONLY] For the accordion headers, can you please update the titles to -- 

Bagages et maroquinerie
Bijoux et montres
Parfums

**Comment by mgc-codigo** [comment]
[BOTH] Can you put watches last? 
1. luggage and leather
2. perfumes
3. watches and jewels

**Comment by mgc-codigo** [comment]
[consideration]

we don't use an "&" anywhere else on the site, specifically the brand section. do we change that to "and" or do we update the way we use "and" in the brand section?

**Comment by artrodriguezcabrera** [comment]
@mgc-codigo 

I updated per your above comments.  Pushed changes to staging.   

Waiting on client feedback before we push to `main` production.

**Pull request merged**
